"""院内知识库 —— 指南 / 药品说明书 / 病历书写规范的原文片段。

⚠️ 重要声明：以下条目由公开指南与说明书的要点摘录整理而成，**仅供临床参考**。
实际诊疗决策应以最新权威指南、药品说明书及院内规范为准；
正式上线的知识库应由院内药学部/质控科提供并做版本化管理。
"""

from __future__ import annotations

KB: list[dict] = [
    {
        "chunk_id": "kb_dm_001",
        "doc_id": "dm_guideline_2020",
        "source": "中国2型糖尿病防治指南（2020年版）",
        "doc_type": "guideline",
        "department": "内分泌科",
        "year": 2020,
        "chapter": "第5章 药物治疗",
        "section": "5.3 二甲双胍",
        "page": 47,
        "text": "二甲双胍是2型糖尿病患者控制高血糖的一线用药和药物联合中的基本用药。如无禁忌证且能够耐受，二甲双胍应一直保留在糖尿病的药物治疗方案中。二甲双胍的主要作用机制是减少肝脏葡萄糖的输出并改善外周胰岛素抵抗。",
    },
    {
        "chunk_id": "kb_dm_002",
        "doc_id": "dm_guideline_2020",
        "source": "中国2型糖尿病防治指南（2020年版）",
        "doc_type": "guideline",
        "department": "内分泌科",
        "year": 2020,
        "chapter": "第5章 药物治疗",
        "section": "5.3 二甲双胍的禁忌证与肾功能要求",
        "page": 48,
        "text": "二甲双胍禁用于肾功能不全患者：估算肾小球滤过率（eGFR）<45 ml·min⁻¹·(1.73 m²)⁻¹ 时禁用；eGFR 45~59 ml·min⁻¹·(1.73 m²)⁻¹ 之间应减量使用并加强肾功能监测。此外，严重感染、脱水、缺氧状态、糖尿病酮症酸中毒等急性状态应暂停使用。",
    },
    {
        "chunk_id": "kb_dm_003",
        "doc_id": "dm_guideline_2020",
        "source": "中国2型糖尿病防治指南（2020年版）",
        "doc_type": "guideline",
        "department": "内分泌科",
        "year": 2020,
        "chapter": "第3章 诊断与分型",
        "section": "3.2 糖尿病诊断标准",
        "page": 22,
        "text": "糖尿病的诊断标准为：具有典型糖尿病症状（烦渴多饮、多尿、多食、不明原因体重下降）加上随机血糖≥11.1 mmol/L，或加上空腹血糖≥7.0 mmol/L，或加上口服葡萄糖耐量试验2小时血糖≥11.1 mmol/L，或加上糖化血红蛋白≥6.5%。无典型症状者需改日复查确认。",
    },
    {
        "chunk_id": "kb_dm_004",
        "doc_id": "dm_guideline_2020",
        "source": "中国2型糖尿病防治指南（2020年版）",
        "doc_type": "guideline",
        "department": "内分泌科",
        "year": 2020,
        "chapter": "第7章 并发症与合并症",
        "section": "7.4 糖尿病肾病的筛查",
        "page": 63,
        "text": "2型糖尿病患者在诊断时即应进行肾脏病变筛查，包括尿白蛋白/肌酐比值（UACR）和估算肾小球滤过率（eGFR）。此后每年至少筛查一次。当eGFR<60 ml·min⁻¹·(1.73 m²)⁻¹ 或 UACR≥30 mg/g 时，应评估为糖尿病肾病并调整降糖药物方案。",
    },
    {
        "chunk_id": "kb_dm_005",
        "doc_id": "dm_guideline_2020",
        "source": "中国2型糖尿病防治指南（2020年版）",
        "doc_type": "guideline",
        "department": "内分泌科",
        "year": 2020,
        "chapter": "第8章 低血糖",
        "section": "8.1 低血糖的定义与分级",
        "page": 72,
        "text": "糖尿病患者血糖低于3.9 mmol/L即应判定为低血糖。严重低血糖指需要他人帮助的低血糖事件，常表现为意识障碍。使用胰岛素或磺脲类药物的患者应重点宣教低血糖识别与自救（立即口服15~20 g葡萄糖，15分钟后复测）。",
    },
    {
        "chunk_id": "kb_bp_001",
        "doc_id": "bp_guideline_2018",
        "source": "中国高血压防治指南（2018年修订版）",
        "doc_type": "guideline",
        "department": "心血管内科",
        "year": 2018,
        "chapter": "第3章 诊断与评估",
        "section": "3.1 血压测量与诊断标准",
        "page": 16,
        "text": "在未使用降压药物的情况下，非同日3次测量诊室血压，收缩压≥140 mmHg和（或）舒张压≥90 mmHg可诊断为高血压。家庭自测血压的诊断标准为≥135/85 mmHg，动态血压24小时平均≥130/80 mmHg。诊断前应排除白大衣高血压。",
    },
    {
        "chunk_id": "kb_bp_002",
        "doc_id": "bp_guideline_2018",
        "source": "中国高血压防治指南（2018年修订版）",
        "doc_type": "guideline",
        "department": "心血管内科",
        "year": 2018,
        "chapter": "第5章 治疗",
        "section": "5.2 降压目标",
        "page": 32,
        "text": "一般高血压患者降压目标为低于140/90 mmHg，能耐受者可进一步降至低于130/80 mmHg。65~79岁老年人首先降至低于150/90 mmHg，如能耐受可降至低于140/90 mmHg。合并糖尿病、冠心病或心力衰竭的患者，血压应控制在低于130/80 mmHg。",
    },
    {
        "chunk_id": "kb_bp_003",
        "doc_id": "bp_guideline_2018",
        "source": "中国高血压防治指南（2018年修订版）",
        "doc_type": "guideline",
        "department": "心血管内科",
        "year": 2018,
        "chapter": "第5章 治疗",
        "section": "5.4 降压药物的选择",
        "page": 37,
        "text": "常用的五大类降压药包括钙通道阻滞剂（CCB）、血管紧张素转换酶抑制剂（ACEI）、血管紧张素受体拮抗剂（ARB）、利尿剂和β受体阻滞剂。对血压≥160/100 mmHg或高于目标血压20/10 mmHg的高危患者，可起始联合治疗，推荐ACEI或ARB与CCB或利尿剂联合。",
    },
    {
        "chunk_id": "kb_bp_004",
        "doc_id": "bp_guideline_2018",
        "source": "中国高血压防治指南（2018年修订版）",
        "doc_type": "guideline",
        "department": "心血管内科",
        "year": 2018,
        "chapter": "第4章 危险分层",
        "section": "4.3 心血管风险分层",
        "page": 27,
        "text": "高血压患者的心血管风险分层需综合血压水平、危险因素、靶器官损害及合并临床疾病。合并糖尿病、慢性肾病、冠心病或脑卒中者直接判定为高危或很高危，需立即启动药物治疗并同时进行危险因素综合管理。",
    },
    {
        "chunk_id": "kb_cap_001",
        "doc_id": "cap_guideline_2016",
        "source": "中国成人社区获得性肺炎诊断和治疗指南（2016年版）",
        "doc_type": "guideline",
        "department": "呼吸内科",
        "year": 2016,
        "chapter": "第2章 诊断",
        "section": "2.1 诊断标准",
        "page": 8,
        "text": "社区获得性肺炎（CAP）的诊断需同时满足：社区发病；肺炎相关临床表现，如新近出现的咳嗽、咳痰或原有呼吸道症状加重，伴或不伴脓痰、胸痛、呼吸困难及咯血，发热，肺实变体征和（或）闻及湿性啰音；胸部影像学检查显示新出现的斑片状浸润影、叶或段实变影、磨玻璃影或间质性改变。",
    },
    {
        "chunk_id": "kb_cap_002",
        "doc_id": "cap_guideline_2016",
        "source": "中国成人社区获得性肺炎诊断和治疗指南（2016年版）",
        "doc_type": "guideline",
        "department": "呼吸内科",
        "year": 2016,
        "chapter": "第4章 治疗",
        "section": "4.2 经验性抗感染治疗",
        "page": 19,
        "text": "CAP经验性抗感染治疗应根据患者年龄、基础疾病、病情严重程度及当地病原流行病学选择。门诊轻症患者可选用阿莫西林或呼吸喹诺酮类；需住院的青壮年无基础疾病患者可选用青霉素类、第二代或第三代头孢菌素；重症患者推荐β内酰胺类联合大环内酯类或呼吸喹诺酮类。",
    },
    {
        "chunk_id": "kb_cap_003",
        "doc_id": "cap_guideline_2016",
        "source": "中国成人社区获得性肺炎诊断和治疗指南（2016年版）",
        "doc_type": "guideline",
        "department": "呼吸内科",
        "year": 2016,
        "chapter": "第4章 治疗",
        "section": "4.5 疗效评估与疗程",
        "page": 24,
        "text": "抗感染治疗一般在48~72小时后评估疗效，评估指标包括体温、呼吸道症状、白细胞计数与C反应蛋白等。轻中症CAP疗程一般5~7天，非典型病原体或重症患者适当延长。治疗72小时无改善需重新评估病原学与并发症。",
    },
    {
        "chunk_id": "kb_cap_004",
        "doc_id": "cap_guideline_2016",
        "source": "中国成人社区获得性肺炎诊断和治疗指南（2016年版）",
        "doc_type": "guideline",
        "department": "呼吸内科",
        "year": 2016,
        "chapter": "第3章 病情严重程度评价",
        "section": "3.2 CURB-65评分",
        "page": 14,
        "text": "CURB-65评分包含意识障碍、尿素氮大于7 mmol/L、呼吸频率≥30次/分、收缩压低于90 mmHg或舒张压≤60 mmHg、年龄≥65岁五项，每项1分。评分0~1分可门诊治疗，2分建议住院，3分及以上应评估收入重症监护病房。",
    },
    {
        "chunk_id": "kb_ami_001",
        "doc_id": "stemi_guideline_2019",
        "source": "急性ST段抬高型心肌梗死诊断和治疗指南（2019）",
        "doc_type": "guideline",
        "department": "心血管内科",
        "year": 2019,
        "chapter": "第3章 诊断与危险分层",
        "section": "3.1 临床表现",
        "page": 11,
        "text": "急性心肌梗死典型表现为持续超过20分钟的胸骨后压榨性疼痛，可向左肩、左臂内侧、颈部或下颌放射，常伴大汗、恶心、呼吸困难。老年人、糖尿病患者可表现为不典型症状甚至无痛性心肌梗死，需结合心电图与心肌损伤标志物判断。",
    },
    {
        "chunk_id": "kb_ami_002",
        "doc_id": "stemi_guideline_2019",
        "source": "急性ST段抬高型心肌梗死诊断和治疗指南（2019）",
        "doc_type": "guideline",
        "department": "心血管内科",
        "year": 2019,
        "chapter": "第4章 再灌注治疗",
        "section": "4.1 直接PCI与时间窗",
        "page": 18,
        "text": "直接经皮冠状动脉介入治疗（PCI）是STEMI首选的再灌注方式，要求首次医疗接触至导丝通过靶血管时间不超过90分钟。若预计转运延误使该时间超过120分钟，且症状发作在12小时内无溶栓禁忌，应在30分钟内启动静脉溶栓治疗。",
    },
    {
        "chunk_id": "kb_ami_003",
        "doc_id": "stemi_guideline_2019",
        "source": "急性ST段抬高型心肌梗死诊断和治疗指南（2019）",
        "doc_type": "guideline",
        "department": "心血管内科",
        "year": 2019,
        "chapter": "第5章 抗栓治疗",
        "section": "5.2 抗血小板与抗凝",
        "page": 25,
        "text": "STEMI患者若无禁忌应尽早给予负荷剂量阿司匹林（150~300 mg嚼服）联合P2Y12受体抑制剂双联抗血小板治疗，并根据缺血与出血风险选择抗凝方案。既往有活动性消化道出血者需权衡出血风险并加用质子泵抑制剂。",
    },
    {
        "chunk_id": "kb_ami_004",
        "doc_id": "stemi_guideline_2019",
        "source": "急性ST段抬高型心肌梗死诊断和治疗指南（2019）",
        "doc_type": "guideline",
        "department": "急诊科",
        "year": 2019,
        "chapter": "第6章 急诊处置流程",
        "section": "6.1 胸痛中心流程",
        "page": 31,
        "text": "急性胸痛患者应在首次医疗接触后10分钟内完成18导联心电图检查，并检测肌钙蛋白。对高度怀疑急性冠脉综合征且伴大汗、持续胸痛的患者，应立即启动胸痛中心流程，同时完成心电监护与静脉通路建立，不得因等待检查结果而延误再灌注决策。",
    },
    {
        "chunk_id": "kb_stroke_001",
        "doc_id": "ais_guideline_2018",
        "source": "中国急性缺血性脑卒中诊治指南（2018）",
        "doc_type": "guideline",
        "department": "神经内科",
        "year": 2018,
        "chapter": "第4章 急性期治疗",
        "section": "4.1 静脉溶栓",
        "page": 20,
        "text": "对发病4.5小时内的急性缺血性脑卒中患者，应尽快给予阿替普酶静脉溶栓治疗，推荐剂量0.9 mg/kg（最大剂量90 mg）。溶栓前必须完成头颅CT排除出血，并核对禁忌证。给药时间每提前1分钟可显著改善预后。",
    },
    {
        "chunk_id": "kb_stroke_002",
        "doc_id": "ais_guideline_2018",
        "source": "中国急性缺血性脑卒中诊治指南（2018）",
        "doc_type": "guideline",
        "department": "神经内科",
        "year": 2018,
        "chapter": "第3章 急诊评估",
        "section": "3.2 快速识别与量表",
        "page": 12,
        "text": "急诊接诊疑似卒中患者时，应在10分钟内完成NIHSS评分与头颅CT检查。推荐采用FAST或中风120口诀进行公众识别：面部不对称、单侧肢体无力、言语不清。疑似卒中患者应优先进入卒中绿色通道。",
    },
    {
        "chunk_id": "kb_lipid_001",
        "doc_id": "lipid_guideline_2016",
        "source": "中国成人血脂异常防治指南（2016年修订版）",
        "doc_type": "guideline",
        "department": "心血管内科",
        "year": 2016,
        "chapter": "第5章 治疗",
        "section": "5.3 LDL-C目标值",
        "page": 29,
        "text": "血脂异常的治疗以降低低密度脂蛋白胆固醇（LDL-C）为首要目标。极高危患者LDL-C应降至低于1.8 mmol/L，高危患者降至低于2.6 mmol/L，中低危患者降至低于3.4 mmol/L。他汀类药物是首选调脂药物，起始治疗4~6周后应复查血脂与肝功能。",
    },
    {
        "chunk_id": "kb_lipid_002",
        "doc_id": "lipid_guideline_2016",
        "source": "中国成人血脂异常防治指南（2016年修订版）",
        "doc_type": "guideline",
        "department": "心血管内科",
        "year": 2016,
        "chapter": "第5章 治疗",
        "section": "5.5 他汀的安全性监测",
        "page": 34,
        "text": "使用他汀类药物期间应关注肝脏转氨酶与肌酸激酶。转氨酶升高超过正常上限3倍或出现肌痛伴肌酸激酶升高超过正常上限5倍时应停药并评估原因。启动治疗前建议检测基线肝功能与血脂。",
    },
    {
        "chunk_id": "kb_fever_001",
        "doc_id": "child_fever_2016",
        "source": "中国0至5岁儿童病因不明急性发热诊断处理指南",
        "doc_type": "guideline",
        "department": "儿科",
        "year": 2016,
        "chapter": "第3章 退热治疗",
        "section": "3.1 退热药物选择",
        "page": 15,
        "text": "2月龄以上儿童推荐口服对乙酰氨基酚每次15 mg/kg，间隔6小时；6月龄以上儿童可选用布洛芬每次10 mg/kg，间隔6~8小时。不推荐两种退热药联合或交替使用，也不推荐使用糖皮质激素作为退热剂。退热的目的在于改善舒适度而非单纯降低体温数值。",
    },
    {
        "chunk_id": "kb_fever_002",
        "doc_id": "child_fever_2016",
        "source": "中国0至5岁儿童病因不明急性发热诊断处理指南",
        "doc_type": "guideline",
        "department": "儿科",
        "year": 2016,
        "chapter": "第2章 评估与预警",
        "section": "2.3 危急征象",
        "page": 9,
        "text": "儿童发热伴下列征象提示严重疾病：3月龄以下体温≥38 ℃、精神反应差或嗜睡、呼吸增快伴三凹征、皮肤花斑或发花、毛细血管再充盈时间大于3秒、惊厥、颈项强直、持续拒食或尿量明显减少。出现任一征象应立即转入急诊评估。",
    },
    {
        "chunk_id": "kb_drug_meta_001",
        "doc_id": "label_metformin",
        "source": "盐酸二甲双胍片说明书",
        "doc_type": "label",
        "department": "药学部",
        "year": 2020,
        "chapter": "禁忌",
        "section": "禁用人群",
        "page": 2,
        "text": "盐酸二甲双胍片禁忌包括：对本品过敏者；中重度肾功能不全（eGFR低于45 ml/min/1.73 m²）者；急性或慢性代谢性酸中毒，包括糖尿病酮症酸中毒者；严重感染、脱水和休克等可导致组织缺氧的疾病；严重肝功能不全者。",
    },
    {
        "chunk_id": "kb_drug_meta_002",
        "doc_id": "label_metformin",
        "source": "盐酸二甲双胍片说明书",
        "doc_type": "label",
        "department": "药学部",
        "year": 2020,
        "chapter": "用法用量",
        "section": "用法",
        "page": 2,
        "text": "盐酸二甲双胍片起始剂量为一次0.5 g，一日2次，随餐服用；根据血糖情况每1~2周调整一次剂量，最大推荐剂量为一日2550 mg。eGFR在45~59 ml/min/1.73 m²之间者应减量服用并密切监测肾功能。",
    },
    {
        "chunk_id": "kb_drug_meta_003",
        "doc_id": "label_metformin",
        "source": "盐酸二甲双胍片说明书",
        "doc_type": "label",
        "department": "药学部",
        "year": 2020,
        "chapter": "注意事项",
        "section": "碘造影剂使用",
        "page": 3,
        "text": "接受血管内注射碘化造影剂检查的患者，应暂时停用二甲双胍，检查后至少48小时复查肾功能无恶化方可恢复用药。用药期间应定期监测肾功能与血乳酸浓度。老年患者应定期检查肾功能，根据肾功能调整剂量。",
    },
    {
        "chunk_id": "kb_drug_aspirin_001",
        "doc_id": "label_aspirin",
        "source": "阿司匹林肠溶片说明书",
        "doc_type": "label",
        "department": "药学部",
        "year": 2018,
        "chapter": "禁忌",
        "section": "禁用人群",
        "page": 2,
        "text": "阿司匹林肠溶片禁忌包括：对阿司匹林或其他非甾体抗炎药过敏者；活动性消化性溃疡、出血体质或既往有消化道出血病史者；阿司匹林哮喘患者；严重肝肾功能衰竭、严重心力衰竭者；妊娠晚期妇女。",
    },
    {
        "chunk_id": "kb_drug_aspirin_002",
        "doc_id": "label_aspirin",
        "source": "阿司匹林肠溶片说明书",
        "doc_type": "label",
        "department": "药学部",
        "year": 2018,
        "chapter": "药物相互作用",
        "section": "相互作用",
        "page": 4,
        "text": "阿司匹林与抗凝药（华法林、肝素）合用可增加出血风险；与甲氨蝶呤合用可增加其毒性；与布洛芬等非甾体抗炎药合用可能减弱阿司匹林的抗血小板作用；与糖皮质激素合用增加胃肠道出血风险。合并用药期间应监测出血征象。",
    },
    {
        "chunk_id": "kb_drug_warfarin_001",
        "doc_id": "label_warfarin",
        "source": "华法林钠片说明书",
        "doc_type": "label",
        "department": "药学部",
        "year": 2017,
        "chapter": "注意事项",
        "section": "INR监测",
        "page": 3,
        "text": "华法林治疗窗窄、个体差异大，用药期间必须定期监测凝血酶原时间与国际标准化比值（INR）。多数适应证INR目标范围为2.0~3.0，机械瓣膜置换术后可放宽至2.5~3.5。起始治疗阶段建议每2~3天监测一次，稳定后可延长至每4周一次。",
    },
    {
        "chunk_id": "kb_drug_abx_001",
        "doc_id": "abx_principle_2015",
        "source": "抗菌药物临床应用指导原则（2015年版）",
        "doc_type": "guideline",
        "department": "药学部",
        "year": 2015,
        "chapter": "第2章 抗菌药物临床应用管理",
        "section": "2.4 联合用药指征",
        "page": 12,
        "text": "抗菌药物联合应用应有明确指征：病原菌未明的严重感染、单一药物不能控制的混合感染、需长期用药且易产生耐药性的感染。联合用药应在病历中记录指征与依据，避免无指征联合导致不良反应与耐药风险增加。",
    },
    {
        "chunk_id": "kb_drug_abx_002",
        "doc_id": "abx_principle_2015",
        "source": "抗菌药物临床应用指导原则（2015年版）",
        "doc_type": "guideline",
        "department": "药学部",
        "year": 2015,
        "chapter": "第3章 治疗性应用",
        "section": "3.1 用药前标本送检",
        "page": 18,
        "text": "治疗性应用抗菌药物前，应尽可能留取相应标本做病原学检查，包括血培养、痰培养、尿培养等，并在病程记录中记录送检情况。获得病原学结果后应及时评估是否需要调整为目标性治疗。",
    },
    {
        "chunk_id": "kb_record_001",
        "doc_id": "record_norm_2010",
        "source": "病历书写基本规范（2010年版）",
        "doc_type": "norm",
        "department": "质控科",
        "year": 2010,
        "chapter": "第3章 住院病历书写要求",
        "section": "3.5 主诉",
        "page": 5,
        "text": "主诉是指促使患者就诊的主要症状（或体征）及持续时间。主诉应用一两句话加以概括，并同时注明持续的时间，例如反复胸闷3天。主诉应当准确反映患者本次就诊的主要问题，不得使用诊断名称代替症状。",
    },
    {
        "chunk_id": "kb_record_002",
        "doc_id": "record_norm_2010",
        "source": "病历书写基本规范（2010年版）",
        "doc_type": "norm",
        "department": "质控科",
        "year": 2010,
        "chapter": "第3章 住院病历书写要求",
        "section": "3.6 现病史",
        "page": 6,
        "text": "现病史是指患者本次疾病的发生、演变、诊疗等方面的详细情况，应当按时间顺序书写，内容包括发病情况（发病时间、地点、起病缓急、前驱症状、可能的病因和诱因）、主要症状特点及其发展变化情况、伴随症状、发病以来诊治经过及结果、发病以来一般情况。",
    },
    {
        "chunk_id": "kb_record_003",
        "doc_id": "record_norm_2010",
        "source": "病历书写基本规范（2010年版）",
        "doc_type": "norm",
        "department": "质控科",
        "year": 2010,
        "chapter": "第3章 住院病历书写要求",
        "section": "3.12 病程记录",
        "page": 9,
        "text": "病程记录是指继入院记录之后，对患者病情和诊疗过程所进行的连续性记录。内容包括患者的病情变化情况、重要的辅助检查结果及临床意义、上级医师查房意见、会诊意见、医师分析讨论意见、所采取的诊疗措施及效果、医嘱更改及理由。",
    },
    {
        "chunk_id": "kb_record_004",
        "doc_id": "record_rule_2013",
        "source": "医疗机构病历管理规定（2013年版）",
        "doc_type": "norm",
        "department": "质控科",
        "year": 2013,
        "chapter": "第2章 病历书写时限",
        "section": "2.3 时限要求",
        "page": 4,
        "text": "入院记录应当于患者入院后24小时内完成；首次病程记录应当在患者入院后8小时内完成；日常病程记录中，一般患者至少每3天记录一次，病情稳定的慢性病患者可适当延长，危重患者应当根据病情需要随时记录。手术记录应当在术后24小时内完成。",
    },
    {
        "chunk_id": "kb_record_005",
        "doc_id": "record_norm_2010",
        "source": "病历书写基本规范（2010年版）",
        "doc_type": "norm",
        "department": "质控科",
        "year": 2010,
        "chapter": "第3章 住院病历书写要求",
        "section": "3.4 既往史与过敏史",
        "page": 5,
        "text": "既往史是指患者过去的健康和疾病情况，包括既往一般健康状况、疾病史、传染病史、预防接种史、手术外伤史、输血史及过敏史。过敏史应具体记录过敏原与过敏表现，药物过敏应以醒目标识注明，不得以无简单代替而未核实。",
    },
    {
        "chunk_id": "kb_record_006",
        "doc_id": "record_quality_2018",
        "source": "住院病历质量评价标准（2018年试行）",
        "doc_type": "norm",
        "department": "质控科",
        "year": 2018,
        "chapter": "第2章 内涵质量",
        "section": "2.2 诊断依据",
        "page": 7,
        "text": "诊断依据是指做出初步诊断所依据的症状、体征及辅助检查结果。初步诊断应当有充分的依据支撑，关键检查结果应在病史或病程记录中体现其临床意义分析，不得仅罗列检查数值而不做分析。",
    },
    {
        "chunk_id": "kb_record_007",
        "doc_id": "record_quality_2018",
        "source": "住院病历质量评价标准（2018年试行）",
        "doc_type": "norm",
        "department": "质控科",
        "year": 2018,
        "chapter": "第2章 内涵质量",
        "section": "2.5 用药与医嘱一致性",
        "page": 11,
        "text": "医嘱与病程记录应当保持一致：更改用药方案应在病程记录中说明理由；使用或调整抗菌药物应有指征记录；出现异常检验结果应在病程记录中分析并记录相应处理措施。",
    },
    {
        "chunk_id": "kb_safe_001",
        "doc_id": "patient_safety_2019",
        "source": "患者安全目标（2019年版）",
        "doc_type": "norm",
        "department": "医务科",
        "year": 2019,
        "chapter": "目标三 用药安全",
        "section": "高危药品管理",
        "page": 5,
        "text": "医疗机构应建立高危药品管理制度，对高浓度电解质、抗凝药、胰岛素、化疗药等实施专区存放、双人核对。使用高危药品应在医嘱与执行记录中体现核对流程，确保用药安全可追溯。",
    },
    {
        "chunk_id": "kb_safe_002",
        "doc_id": "patient_safety_2019",
        "source": "患者安全目标（2019年版）",
        "doc_type": "norm",
        "department": "医务科",
        "year": 2019,
        "chapter": "目标五 危急值报告",
        "section": "危急值处置",
        "page": 8,
        "text": "医疗机构应建立危急值报告制度，明确危急值项目与报告流程。接到危急值报告后，接收人员应复述确认并立即通知主管医师，医师应在规定时间内评估患者并采取处理措施，处理过程应当在病程记录中体现。",
    },
    {
        "chunk_id": "kb_safe_003",
        "doc_id": "triage_norm_2020",
        "source": "急诊预检分诊分级标准（2020年版）",
        "doc_type": "norm",
        "department": "急诊科",
        "year": 2020,
        "chapter": "第2章 分级标准",
        "section": "2.2 一级与二级患者",
        "page": 3,
        "text": "一级为濒危患者，需立即抢救；二级为危重患者，存在潜在生命危险，应在10分钟内接受诊治。胸痛伴大汗、意识障碍、呼吸困难、活动性出血等属于二级及以上，应直接进入抢救区，不得在普通候诊区等候。",
    },
    {
        "chunk_id": "kb_safe_004",
        "doc_id": "informed_consent_2010",
        "source": "医疗机构管理条例实施细则",
        "doc_type": "norm",
        "department": "医务科",
        "year": 2010,
        "chapter": "第4章 知情同意",
        "section": "4.1 应当取得书面同意的情形",
        "page": 6,
        "text": "医疗机构实施手术、特殊检查、特殊治疗时，应当向患者本人说明医疗风险、替代医疗方案等情况，并取得其书面同意。患者不具备完全民事行为能力时，应向其法定代理人说明并取得书面同意。手术同意书应当由患者本人或其法定代理人签名。",
    },
]

DOCUMENTS: dict[str, dict] = {}
for _chunk in KB:
    entry = DOCUMENTS.setdefault(
        _chunk["doc_id"],
        {
            "doc_id": _chunk["doc_id"],
            "source": _chunk["source"],
            "doc_type": _chunk["doc_type"],
            "department": _chunk["department"],
            "year": _chunk["year"],
            "chunks": 0,
        },
    )
    entry["chunks"] += 1


def kb_stats() -> dict:
    return {
        "documents": len(DOCUMENTS),
        "chunks": len(KB),
        "departments": sorted({d["department"] for d in DOCUMENTS.values()}),
        "notice": "知识条目仅供临床参考，最终以最新指南与院内规范为准",
    }
